# Generated by Django 6.1 on 2026-08-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('policy_version', models.CharField(max_length=20)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
